---
- name: playbook to install Zed Code Editor
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: zed
        gpg_key: https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc
        repository_url: https://debian.griffo.io/apt
        suites: trixie
        components: main
